name: System-1.19
version: 0.1
main: de.adam.main.PlaycenSystemV2
api-version: 1.19
commands:
   gamemode:
      aliases: gm
   setspawn:
   clearlag:
   chatclear:
      aliases: cc,clearchat
   werkbank:
      aliases: wb
