name: System-1.19
version: 0.1
main: de.adam.cbsystemv1.main.ZockerWorldCBV1
api-version: 1.19
softdepend: []
depend: [GlobalSystem, Vault, PlotSquared]
commands:
   setspawn:
   clearlag:
   werkbank:
      aliases: [wb]
   sign:
   customitem:
      aliases: [ci]
   setshop: